[tools]
emsdk = "latest"
go = "latest"
npm = "11"
"npm:eslint" = "latest"
"npm:eslint-config-treesitter" = "latest"
"npm:node-addon-api" = "latest"
"npm:node-gyp" = "latest"
"npm:node-gyp-build" = "latest"
"pipx:build" = "latest"
"pipx:twine" = "latest"
python = "3"
rust = "latest"
swift = "latest"
tree-sitter = "latest"
