name: Generate

on:
  push:
    branches: [main]
    paths:
      - grammar.js

  pull_request:
    paths:
      - grammar.js

jobs:
  generate:
    name: Generate parser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup tree-sitter tooling
        uses: tree-sitter/setup-action@v2
        with:
          install-lib: false

      - name: Run parser generator
        run: tree-sitter generate
