name: Test

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

  pull_request:
    paths:
      - grammar.js
      - src/**
      - bindings/**
      - binding.gyp

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup tree-sitter tooling
        uses: tree-sitter/setup-action/cli@v2

      - name: Run included tests
        uses: tree-sitter/parser-test-action@v3
        with:
          test-rust: true
